/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutActionSheet: typeof import('@nutui/nutui')['ActionSheet']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutBadge: typeof import('@nutui/nutui')['Badge']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCard: typeof import('@nutui/nutui')['Card']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui')['Checkbox']
    NutEmpty: typeof import('@nutui/nutui')['Empty']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutInputNumber: typeof import('@nutui/nutui')['InputNumber']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutProgress: typeof import('@nutui/nutui')['Progress']
    NutRadio: typeof import('@nutui/nutui')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui')['RadioGroup']
    NutRange: typeof import('@nutui/nutui')['Range']
    NutRate: typeof import('@nutui/nutui')['Rate']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutSwitch: typeof import('@nutui/nutui')['Switch']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTag: typeof import('@nutui/nutui')['Tag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NutActionSheet: typeof import('@nutui/nutui')['ActionSheet']
  const NutAvatar: typeof import('@nutui/nutui')['Avatar']
  const NutBadge: typeof import('@nutui/nutui')['Badge']
  const NutButton: typeof import('@nutui/nutui')['Button']
  const NutCard: typeof import('@nutui/nutui')['Card']
  const NutCell: typeof import('@nutui/nutui')['Cell']
  const NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
  const NutCheckbox: typeof import('@nutui/nutui')['Checkbox']
  const NutEmpty: typeof import('@nutui/nutui')['Empty']
  const NutForm: typeof import('@nutui/nutui')['Form']
  const NutFormItem: typeof import('@nutui/nutui')['FormItem']
  const NutInput: typeof import('@nutui/nutui')['Input']
  const NutInputNumber: typeof import('@nutui/nutui')['InputNumber']
  const NutNavbar: typeof import('@nutui/nutui')['Navbar']
  const NutProgress: typeof import('@nutui/nutui')['Progress']
  const NutRadio: typeof import('@nutui/nutui')['Radio']
  const NutRadioGroup: typeof import('@nutui/nutui')['RadioGroup']
  const NutRange: typeof import('@nutui/nutui')['Range']
  const NutRate: typeof import('@nutui/nutui')['Rate']
  const NutSwiper: typeof import('@nutui/nutui')['Swiper']
  const NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
  const NutSwitch: typeof import('@nutui/nutui')['Switch']
  const NutTabbar: typeof import('@nutui/nutui')['Tabbar']
  const NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
  const NutTag: typeof import('@nutui/nutui')['Tag']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}