/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/example/': RouteRecordInfo<
      '/example/',
      '/example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/list/': RouteRecordInfo<
      '/list/',
      '/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/list/details/': RouteRecordInfo<
      '/list/details/',
      '/list/details',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mine/': RouteRecordInfo<
      '/mine/',
      '/mine',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/example/index.vue': {
      routes:
        | '/example/'
      views:
        | never
    }
    'src/views/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/views/list/index.vue': {
      routes:
        | '/list/'
      views:
        | never
    }
    'src/views/list/details/index.vue': {
      routes:
        | '/list/details/'
      views:
        | never
    }
    'src/views/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/views/mine/index.vue': {
      routes:
        | '/mine/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
