/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppErrorBoundary: typeof import('./../src/components/common/AppErrorBoundary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarCounter: typeof import('@varlet/ui')['_CounterComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
    VarRadio: typeof import('@varlet/ui')['_RadioComponent']
    VarRadioGroup: typeof import('@varlet/ui')['_RadioGroupComponent']
    VarRate: typeof import('@varlet/ui')['_RateComponent']
    VarSkeleton: typeof import('@varlet/ui')['_SkeletonComponent']
    VarSlider: typeof import('@varlet/ui')['_SliderComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
  }
}

// For TSX support
declare global {
  const AppErrorBoundary: typeof import('./../src/components/common/AppErrorBoundary.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
  const VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
  const VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
  const VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
  const VarButton: typeof import('@varlet/ui')['_ButtonComponent']
  const VarCell: typeof import('@varlet/ui')['_CellComponent']
  const VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
  const VarChip: typeof import('@varlet/ui')['_ChipComponent']
  const VarCounter: typeof import('@varlet/ui')['_CounterComponent']
  const VarDivider: typeof import('@varlet/ui')['_DividerComponent']
  const VarIcon: typeof import('@varlet/ui')['_IconComponent']
  const VarInput: typeof import('@varlet/ui')['_InputComponent']
  const VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
  const VarRadio: typeof import('@varlet/ui')['_RadioComponent']
  const VarRadioGroup: typeof import('@varlet/ui')['_RadioGroupComponent']
  const VarRate: typeof import('@varlet/ui')['_RateComponent']
  const VarSkeleton: typeof import('@varlet/ui')['_SkeletonComponent']
  const VarSlider: typeof import('@varlet/ui')['_SliderComponent']
  const VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  const VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
}