/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChatInput: typeof import('./../src/components/ai/AiChatInput.vue')['default']
    AppErrorBoundary: typeof import('./../src/components/common/AppErrorBoundary.vue')['default']
    LoginForm: typeof import('./../src/components/auth/LoginForm.vue')['default']
    MarkdownContent: typeof import('./../src/components/ai/MarkdownContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanProgress: typeof import('vant/es')['Progress']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRate: typeof import('vant/es')['Rate']
    VanSlider: typeof import('vant/es')['Slider']
    VanSpace: typeof import('vant/es')['Space']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}

// For TSX support
declare global {
  const AiChatInput: typeof import('./../src/components/ai/AiChatInput.vue')['default']
  const AppErrorBoundary: typeof import('./../src/components/common/AppErrorBoundary.vue')['default']
  const LoginForm: typeof import('./../src/components/auth/LoginForm.vue')['default']
  const MarkdownContent: typeof import('./../src/components/ai/MarkdownContent.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default']
  const VanBadge: typeof import('vant/es')['Badge']
  const VanButton: typeof import('vant/es')['Button']
  const VanCell: typeof import('vant/es')['Cell']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanCheckbox: typeof import('vant/es')['Checkbox']
  const VanDivider: typeof import('vant/es')['Divider']
  const VanEmpty: typeof import('vant/es')['Empty']
  const VanField: typeof import('vant/es')['Field']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanNoticeBar: typeof import('vant/es')['NoticeBar']
  const VanProgress: typeof import('vant/es')['Progress']
  const VanRadio: typeof import('vant/es')['Radio']
  const VanRadioGroup: typeof import('vant/es')['RadioGroup']
  const VanRate: typeof import('vant/es')['Rate']
  const VanSlider: typeof import('vant/es')['Slider']
  const VanSpace: typeof import('vant/es')['Space']
  const VanStepper: typeof import('vant/es')['Stepper']
  const VanSwitch: typeof import('vant/es')['Switch']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
  const VanTag: typeof import('vant/es')['Tag']
}